"""Add role column to User

Revision ID: 03194b3040ab
Revises: 
Create Date: 2026-01-11 17:49:17.999753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03194b3040ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
